### ISSUE TITLE
remove/optional automatic type conversion

### ISSUE THREAD

**Issue by CroneKorkN** [luqasz/librouteros#176]
Hi luqasz,

Thank you for your effort!

We are using librouteros in a config management system and need the exact answer of routeros. The automatic mangeling of `'true'` and `'yes'` into `True` makes it impossible to check precisely, whether a supplied value has successfully been set.

https://github.com/luqasz/librouteros/blob/master/librouteros/protocol.py#L26

I would suggest introducing an environment variable or some sort of module level setting to circumvent the code. Or by removing it entirely, because i can not imagine a use case, where you want the actual result of your request to be hidden from you.

**Comment by luqasz** [comment]
Hi

Please provide your use case where it matters for you. Conversion works in both ways. If you specify `enabled=True` it will be converted to valid API equivalent.

**Comment by trehn** [comment]
We ran into this when trying to manage the `edge` property of a bridge port: https://wiki.mikrotik.com/wiki/Manual:Interface/Bridge#Port_Settings

It takes one of these values: `auto`, `no`, `no-discover`, `yes`, `yes-discover`

Now when we retrieve the state of the port from the device, librouteros might tell us `"edge": True` if it has been set to `"yes"`. When we then try to write that same value back to the device, librouteros will turn `"edge": True` into `"edge": "true"` which is not an allowed value for `edge`. Therefore we cannot write back what librouteros gives us and would have to implement specific logic for these cases that knows about properties that only take `"yes"` instead of `"true"`. We wouldn't need that logic if we could work with the value as returned by the device.

**Comment by luqasz** [comment]
If you pass `True` it will be converted to `yes`. `yes-discover` won't be changed to `True-discover`.

**Comment by trehn** [comment]
I picked the wrong example. We already treat `True` as `"true"` and that's what caused the problem with `"yes"`. If we do it the other way around and treat `True` as `"yes"`, we'll run into problems with properties that only accept `"true"`. It may work if all properties that accept `"true"` will also take `"yes"`, but I'm not sure of that.

**Comment by trehn** [comment]
I guess this rather confusing discussion can be distilled down to:

Are you sure the conversion you're doing here https://github.com/luqasz/librouteros/blob/master/librouteros/protocol.py#L37 is **always** safe? That even though the device might have returned `"true"`, you can always write `"yes"` back to the device? If that's the case, we can fix the issue on our end.

**Comment by luqasz** [comment]
Older devices with firmware 3.x accepted yes/true no/false while 4.x and later accepts only yes, no.

**Comment by trehn** [comment]
Seems to work fine that way, thanks and sorry for the noise.

**Comment by luqasz** [comment]
No problem
